version: "3.8"

services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development
